#if !canImport(ObjectiveC)
import XCTest

extension VaporTestUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VaporTestUtilsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VaporTestUtilsTests.__allTests__VaporTestUtilsTests),
    ]
}
#endif
