#if !canImport(ObjectiveC)
import XCTest

extension ExampleAppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleAppTests = [
        ("testLinuxTestSuiteIncludesAllTests", testLinuxTestSuiteIncludesAllTests),
        ("testMyApp", testMyApp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExampleAppTests.__allTests__ExampleAppTests),
    ]
}
#endif
